[package]
name = "tgfeed-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
teloxide = { version = "0.17.0", features = ["macros"] }
thiserror = { workspace = true }
tgfeed-common = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
