[package]
name = "tgfeed-common"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
grammers-tl-types = { workspace = true }
teloxide = { workspace = true }
reqwest = { workspace = true }
