[package]
name = "tgfeed-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
